name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Streamlit App
        run: |
          curl -L --max-redirs 10 \
          "https://ai-powered-stock-evaluationthesis-um6.streamlit.app/"
